version: '3'

services:
  server:
    container_name: server
    networks:
      shared-networks:
        ipv4_address: 192.168.101.79
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "6007:6007"
    env_file:
      - ./.env
    volumes:
      - shared-data:/server

volumes:
  shared-data:

networks:
  shared-networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24
